Repository AY2021S1-CS2113T-T09-1/tp, pull requests merged in 2020-11, with the labels that each got.

#167 Improved List Command replaces Display Command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/HomeCommand.java
  src/main/java/seedu/duke/commands/member/TeamMemberAddCommand.java
  src/main/java/seedu/duke/commands/member/TeamMemberDeleteCommand.java
  src/main/java/seedu/duke/commands/project/ProjectDeleteCommand.java
  src/main/java/seedu/duke/commands/project/ProjectDescriptionCommand.java
  src/main/java/seedu/duke/commands/task/TaskListCommand.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/member/TeamMemberAddCommandTest.java
  src/test/java/seedu/duke/commands/project/ProjectSelectCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug

#169 Fixing pe d issues
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/project/ProjectDoneCommand.java
Labels: priority.High, type.Bug

#173 project description will now be added in home view
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/project/ProjectDescriptionCommand.java
  src/test/java/seedu/duke/commands/project/ProjectDescriptionCommandTest.java
Labels: featureFlaw, priority.High

#174 [Developer Guide] Appendix for UG & Manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#94 Edit task command
  build.gradle
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/TaskEditCommand.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/task/TaskEditCommandTest.java
Labels: priority.High, type.Task, type.Test

#182 List command fix
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/Parser.java
Labels: severity.Medium, type.Bug

#179 Assign projects/tasks to members will not allow assignment of repeated projects/tasks
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/commands/member/TeamMemberAssignToTaskCommand.java
  src/main/java/seedu/duke/member/TeamMember.java
  src/main/java/seedu/duke/task/Task.java
Labels: severity.High, type.Bug

#183 Parser detects extra slashes and duplicate parameters
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/TaskSelectCommand.java
  src/main/java/seedu/duke/commands/task/TaskSortCommand.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/commands/member/TeamMemberAssignToTaskCommandTest.java
  src/test/java/seedu/duke/commands/task/TaskListCommandTest.java
  src/test/java/seedu/duke/commands/task/TaskListTest.java
  src/test/java/seedu/duke/commands/task/TaskSelectCommandTest.java
  src/test/java/seedu/duke/commands/task/TaskSortCommandTest.java
Labels: nonStandardInputs, optional

#175 Home view - additional features
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/project/ProjectDeadlineCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/project/ProjectDeadlineCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Story

#187 Fixed inaccurate UG Commands and organisation
  docs/UserGuide.md
Labels: documentation

#186 Remove command
  build.gradle
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/member/TeamMemberAssignToTaskCommand.java
  src/main/java/seedu/duke/commands/member/TeamMemberDeleteCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/commands/member/TeamMemberAssignToTaskCommandTest.java
  src/test/java/seedu/duke/commands/member/TeamMemberDeleteCommandTest.java
Labels: severity.High, type.Bug

#191 Samuel Leow PPP
  docs/team/samuellleow.md
Labels: documentation

#176 Riaz PPP
  docs/AboutUs.md
  docs/team/riazaham.md
Labels: documentation, priority.High

#193 Delete project command fix
  src/main/java/seedu/duke/commands/project/ProjectDeleteCommand.java
  src/main/java/seedu/duke/member/TeamMember.java
Labels: severity.High, type.Bug

#197 Fixed negative priority
  plantUML/class.puml
  plantUML/model.puml
  plantUML/object.puml
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/commands/task/TaskAssignPriorityCommand.java
Labels: priority.Medium, type.Bug

#199 Hours command fix
  ezmanager.txt
  src/main/java/seedu/ezmanager/commands/member/TeamMemberAssignToTaskCommand.java
  src/main/java/seedu/ezmanager/ui/Ui.java
  src/test/java/seedu/ezmanager/commands/member/TeamMemberDeleteCommandTest.java
  src/test/java/seedu/ezmanager/commands/project/ProjectDeadlineCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.High, type.Bug, type.Enhancement

#198 Project View Aligment
  src/main/java/seedu/ezmanager/ui/Ui.java
  src/test/java/seedu/ezmanager/commands/member/TeamMemberDeleteCommandTest.java
Labels: priority.High, type.Bug
