Repository AY2021S1-CS2113T-T09-1/tp, pull requests merged in 2020-10, with the labels that each got.

#25 Implemented tests for TaskCommand
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/task/Task.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/TaskCommandTest.java
  src/test/java/seedu/duke/TaskListTest.java
  src/test/java/seedu/duke/TaskTest.java
  src/test/java/util/TestUtil.java
Labels: type.Task

#35 Extract Print to Ui Class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/member/AddTeamMemberCommand.java
  src/main/java/seedu/duke/commands/member/ListTeamMembersCommand.java
  src/main/java/seedu/duke/commands/project/ProjectCommand.java
  src/main/java/seedu/duke/commands/project/ProjectListCommand.java
  src/main/java/seedu/duke/commands/project/ProjectSelectCommand.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/commands/task/TaskDeleteCommand.java
  src/main/java/seedu/duke/commands/task/TaskListCommand.java
  src/main/java/seedu/duke/commands/task/TaskSelectCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectList.java
  src/main/java/seedu/duke/task/TaskList.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Task

#40 Week 9: Task Deadline
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/task/TaskList.java
  src/test/java/seedu/duke/TaskCommandTest.java
  src/test/java/seedu/duke/TaskListTest.java
  src/test/java/seedu/duke/TaskTest.java
  src/test/java/seedu/duke/commands/task/TaskListCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#37 Add project description to specified project
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/project/ProjectDescriptionCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectList.java
  src/test/java/seedu/duke/ProjectDescriptionCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Story

#47 Deadline Command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/DeadlineCommand.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/task/TaskList.java
  src/test/java/seedu/duke/TaskCommandTest.java
  src/test/java/seedu/duke/TaskListTest.java
  src/test/java/seedu/duke/TaskTest.java
  src/test/java/seedu/duke/commands/task/TaskListCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#48 Exceptions class implementation
  .github/workflows/gradle.yml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.Medium, type.Enhancement

#50 Extract printing elements
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/member/AddTeamMemberCommand.java
  src/main/java/seedu/duke/commands/project/DeleteProjectCommand.java
  src/main/java/seedu/duke/commands/project/ProjectDescriptionCommand.java
  src/main/java/seedu/duke/commands/project/ProjectListCommand.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/commands/task/TaskDeleteCommand.java
  src/main/java/seedu/duke/commands/task/TaskListCommand.java
  src/main/java/seedu/duke/member/TeamMemberList.java
  src/main/java/seedu/duke/project/ProjectList.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#53 Convert ProjectList and TeamMembersList into ArrayList
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/member/AddTeamMemberCommand.java
  src/main/java/seedu/duke/commands/member/DeleteTeamMemberCommand.java
  src/main/java/seedu/duke/commands/member/ListTeamMembersCommand.java
  src/main/java/seedu/duke/commands/project/DeleteProjectCommand.java
  src/main/java/seedu/duke/commands/project/ProjectCommand.java
  src/main/java/seedu/duke/commands/project/ProjectDescriptionCommand.java
  src/main/java/seedu/duke/commands/project/ProjectListCommand.java
  src/main/java/seedu/duke/commands/project/ProjectSelectCommand.java
  src/main/java/seedu/duke/commands/task/DeadlineCommand.java
  src/main/java/seedu/duke/commands/task/TaskCommand.java
  src/main/java/seedu/duke/commands/task/TaskDeleteCommand.java
  src/main/java/seedu/duke/commands/task/TaskListCommand.java
  src/main/java/seedu/duke/commands/task/TaskSelectCommand.java
  src/main/java/seedu/duke/member/TeamMember.java
  src/main/java/seedu/duke/member/TeamMemberList.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ProjectDescriptionCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#61 Added JUnit test for Project Description command and Select Project command
  src/main/java/seedu/duke/commands/project/ProjectCommand.java
  src/main/java/seedu/duke/commands/project/ProjectSelectCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectList.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ProjectDescriptionCommandTest.java
  src/test/java/seedu/duke/ProjectSelectCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Test

#64 Add Deadline to project and Add jUnit test to Deadline for project
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/project/ProjectDeadlineCommand.java
  src/main/java/seedu/duke/commands/project/ProjectDeleteCommand.java
  src/main/java/seedu/duke/commands/project/ProjectSelectCommand.java
  src/main/java/seedu/duke/commands/task/TaskDeleteCommand.java
  src/main/java/seedu/duke/commands/task/TaskSelectCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ProjectDeadlineCommandTest.java
  src/test/java/seedu/duke/ProjectSelectCommandTest.java
Labels: priority.Medium, type.Story, type.Test

#77 Estimated Time and Actual Time for Tasks
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/task/ActualTimeCommand.java
  src/main/java/seedu/duke/commands/task/EstimatedTimeCommand.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/task/ActualTimeCommandTest.java
  src/test/java/seedu/duke/commands/task/EstimatedTimeCommandTest.java
Labels: priority.High, type.Story

#76 Sort Project by Deadline as default view
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/project/ProjectListCommand.java
  src/main/java/seedu/duke/commands/project/ProjectSelectCommand.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ProjectDeadlineCommandTest.java
  src/test/java/seedu/duke/ProjectListTest.java
  src/test/java/seedu/duke/commands/project/ProjectSelectCommandTest.java
Labels: priority.High, type.Story, type.Test

#90 Member list bug fix
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/member/AssignMemberToProjectCommand.java
  src/main/java/seedu/duke/commands/member/TeamMembersListCommand.java
  src/main/java/seedu/duke/member/TeamMember.java
  src/main/java/seedu/duke/project/Project.java
  src/test/java/seedu/duke/commands/member/AssignMemberToProjectCommandTest.java
Labels: priority.High, type.Bug

#91 JUnit tests.add member.delete member.list member
  src/main/java/seedu/duke/DukeExceptions.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/member/AssignMemberToProjectCommand.java
  src/main/java/seedu/duke/commands/member/TeamMemberDeleteCommand.java
  src/main/java/seedu/duke/commands/member/TeamMembersListCommand.java
  src/test/java/seedu/duke/commands/member/AssignMemberToProjectCommandTest.java
  src/test/java/seedu/duke/commands/member/TeamMemberAddCommandTest.java
  src/test/java/seedu/duke/commands/member/TeamMemberDeleteCommandTest.java
  src/test/java/seedu/duke/commands/member/TeamMembersListCommandTest.java
  src/test/java/seedu/duke/commands/project/ProjectDeadlineCommandTest.java
  src/test/java/seedu/duke/commands/project/ProjectListTest.java
Labels: priority.High, type.Test

#97 Home view
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/PrintHomeViewCommand.java
  src/main/java/seedu/duke/commands/member/AssignMemberToProjectCommand.java
  src/main/java/seedu/duke/commands/member/TeamMembersListCommand.java
  src/main/java/seedu/duke/member/TeamMember.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Story
